version: '3'
services:
  postgres:
    container_name: sanos-postgres
    image: postgres:13
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env
    volumes:
      - sanos-postgres:/var/lib/postgresql

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: sanos-influxdb
    volumes:
      - sanos-influxdbv2:/.influxdbv2
    ports:
      - "${INFLUXDB_PORT}:8086"
    env_file:
      - .env

  influxdb_cli:
    links:
      - influxdb
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: sanos-influxdb-cli
    entrypoint: influx setup --bucket ${INFLUXDB_BUCKET} -t ${INFLUXDB_TOKEN} -o ${INFLUXDB_ORG} --username=${INFLUXDB_USER} --password=${INFLUXDB_PASSWORD} --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on:
      - influxdb
    env_file:
      - .env

volumes:
  sanos-postgres:
  sanos-influxdbv2:
